ALTER TABLE driver_hours ADD COLUMN IF NOT EXISTS original_hours DECIMAL(10, 2) DEFAULT NULL;
ALTER TABLE driver_hours ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE driver_hours ADD COLUMN IF NOT EXISTS edited_by INTEGER REFERENCES users(id) DEFAULT NULL;
ALTER TABLE driver_hours ADD COLUMN IF NOT EXISTS edit_reason TEXT DEFAULT NULL;
